//
//  ResolvableValidationReservedNameReport.swift
//
//
//  Created by Dzmitry Letko on 09/08/2026.
//

import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

extension ResolvableValidation {
    struct ReservedNameReport {
        struct Candidate {
            let name: TokenSyntax
            let node: FunctionDeclSyntax
            let renameable: Bool

            init(_ registrable: Registrable) {
                node = registrable.node
                name = registrable.name
                renameable = true
            }

            init(_ performable: Performable) {
                node = performable.node
                name = performable.name
                renameable = false
            }
        }

        static let reserved: Set<String> = ["resolve", "Resolved", "Resolver", "_registrar", "_resolvable"]

        let candidates: [Candidate]

        static func make(registrables: [Registrable], performables: [Performable]) -> ReservedNameReport {
            let candidates = registrables.map(Candidate.init(_:)) + performables.map(Candidate.init(_:))

            return .init(candidates: candidates.filter { reserved.contains($0.name.text) })
        }

        func print(in context: some MacroExpansionContext) {
            candidates.forEach { candidate in
                let hint = candidate.renameable ? "rename the function or pass a different `name:`" : "rename the function"
                let message = MacroExpansionErrorMessage("'\(candidate.name)' collides with a member generated by `@Resolvable` – \(hint)")
                let diagnostic = Diagnostic(
                    node: candidate.node.name,
                    message: message
                )

                context.diagnose(diagnostic)
            }
        }
    }
}
